// src/app/example/mockData.ts

export type PackageId = "starter" | "growth" | "pro";

export const PACKAGE_CONFIG = {
  starter: {
    id: "starter",
    label: "Starter",
    emoji: "🌱",
    price: "৳500",
    period: "/month",
    commission: "2.5%",
    badge: "Perfect to begin",
    accent: "#6B6B6B",
    accentHover: "#4a4a4a",
    accentLight: "#F7F4F0",
    cardBorder: "#E5E5E5",
    cardBg: "#ffffff",
    dashSidebar: "#2D2D2D",
    tagBg: "#F7F4F0",
    tagText: "#6B6B6B",
    btnClass: "bg-[#2D2D2D] hover:bg-[#444] text-white",
    isMostPopular: false,
    // Feature flags
    maxProducts: "100",
    maxCategories: "10",
    themes: "3 themes",
    hasAdvancedThemes: false,
    hasAnalytics: true, // basic analytics
    hasAdvancedAnalytics: false,
    hasCoupons: false,
    hasFlashSale: false,
    hasSEO: false,
    hasFacebookPixel: false,
    hasAI: false,
    hasStaff: false,
    hasBulkUpload: false,
    hasFeaturedBadge: false,
    hasLoyalty: false,
    hasEmailCampaign: false,
    hasCustomerDB: false,
    hasPrioritySupport: false,
    features: [
      "1 Online Store",
      "Custom URL (nexora.com/shop)",
      "Up to 100 products",
      "10 product categories",
      "Product variants (Size/Color)",
      "Stock management",
      "Order dashboard",
      "Invoice generation",
      "Inside & outside city delivery",
      "Upload logo & banner",
      "Wishlist & reviews",
      "Daily/Weekly/Monthly sales",
      "Basic revenue report",
      "Email support",
    ],
    locked: [
      "Discount coupons",
      "Flash sale",
      "SEO tools",
      "Facebook Pixel",
      "Customer database",
      "AI tools",
      "Staff accounts",
      "Premium badge",
    ],
  },

  growth: {
    id: "growth",
    label: "Growth",
    emoji: "🚀",
    price: "৳1,500",
    period: "/month",
    commission: "2.0%",
    badge: "Most Popular",
    accent: "#FF5C1A",
    accentHover: "#C43A08",
    accentLight: "#FFE8DC",
    cardBorder: "#FF5C1A",
    cardBg: "#ffffff",
    dashSidebar: "#1A1A1A",
    tagBg: "#FFE8DC",
    tagText: "#C43A08",
    btnClass: "bg-orange hover:bg-orange-deep text-white",
    isMostPopular: true,
    maxProducts: "1,000",
    maxCategories: "Unlimited",
    themes: "8 premium themes",
    hasAdvancedThemes: true,
    hasAnalytics: true,
    hasAdvancedAnalytics: true,
    hasCoupons: true,
    hasFlashSale: true,
    hasSEO: true,
    hasFacebookPixel: true,
    hasAI: false,
    hasStaff: false,
    hasBulkUpload: true,
    hasFeaturedBadge: false,
    hasLoyalty: false,
    hasEmailCampaign: false,
    hasCustomerDB: true,
    hasPrioritySupport: true,
    features: [
      "Everything in Starter",
      "Up to 1,000 products",
      "Unlimited categories",
      "8 premium store themes",
      "Bulk upload (Excel)",
      "Product labels (New/Sale/Trending)",
      "Discount coupons & flash sale",
      "Promo banners & featured collections",
      "Customer database",
      "Best/Worst selling products",
      "Revenue charts & order reports",
      "SEO title & description",
      "Google index ready",
      "Facebook Pixel & Google Analytics",
      "Priority & live chat support",
    ],
    locked: [
      "AI product description",
      "AI SEO generator",
      "Staff accounts",
      "Loyalty points",
      "Email campaigns",
      "Premium verified badge",
    ],
  },

  pro: {
    id: "pro",
    label: "Business Pro",
    emoji: "👑",
    price: "৳3,000",
    period: "/month",
    commission: "1.0%",
    badge: "Full power",
    accent: "#7C3AED",
    accentHover: "#6D28D9",
    accentLight: "#F5F3FF",
    cardBorder: "#7C3AED",
    cardBg: "#ffffff",
    dashSidebar: "#1E1B4B",
    tagBg: "#EDE9FE",
    tagText: "#6D28D9",
    btnClass: "bg-[#7C3AED] hover:bg-[#6D28D9] text-white",
    isMostPopular: false,
    maxProducts: "Unlimited",
    maxCategories: "Unlimited",
    themes: "All premium + luxury",
    hasAdvancedThemes: true,
    hasAnalytics: true,
    hasAdvancedAnalytics: true,
    hasCoupons: true,
    hasFlashSale: true,
    hasSEO: true,
    hasFacebookPixel: true,
    hasAI: true,
    hasStaff: true,
    hasBulkUpload: true,
    hasFeaturedBadge: true,
    hasLoyalty: true,
    hasEmailCampaign: true,
    hasCustomerDB: true,
    hasPrioritySupport: true,
    features: [
      "Everything in Growth",
      "Unlimited products & categories",
      "Luxury theme collection",
      "Video banner support",
      "AI product description & SEO",
      "AI marketing captions",
      "Profit & Loss report",
      "Area-wise sales report",
      "Customer growth & conversion report",
      "Staff accounts & permission control",
      "Loyalty points & gift cards",
      "Email & SMS campaigns",
      "Abandoned cart recovery",
      "Premium verified badge ✓",
      "Homepage promotion priority",
      "WhatsApp & Messenger chat",
      "Dedicated account manager",
    ],
    locked: [],
  },
};

export const MOCK_PRODUCTS = [
  { id: "1", name: "iPhone 16 Pro", price: "৳1,40,000", img: "https://images.unsplash.com/photo-1592750475338-74b7b21085ab?w=300&q=80", category: "Phones", stock: 12, badge: "Best seller", sold: 42 },
  { id: "2", name: "Samsung S25 Ultra", price: "৳1,20,000", img: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?w=300&q=80", category: "Phones", stock: 8, badge: null, sold: 28 },
  { id: "3", name: "Logitech MX Master 3", price: "৳9,500", img: "https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=300&q=80", category: "Accessories", stock: 25, badge: "Sale", sold: 65 },
  { id: "4", name: "Sony WH-1000XM5", price: "৳35,000", img: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=300&q=80", category: "Audio", stock: 15, badge: null, sold: 19 },
  { id: "5", name: "MacBook Air M3", price: "৳1,35,000", img: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?w=300&q=80", category: "Laptops", stock: 6, badge: "New", sold: 11 },
  { id: "6", name: "Mechanical Keyboard", price: "৳7,500", img: "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=300&q=80", category: "Accessories", stock: 30, badge: null, sold: 38 },
  { id: "7", name: "Smart Watch Pro", price: "৳22,000", img: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=300&q=80", category: "Wearables", stock: 18, badge: "Trending", sold: 24 },
  { id: "8", name: "Canon EOS R50", price: "৳75,000", img: "https://images.unsplash.com/photo-1502920917128-1aa500764cbd?w=300&q=80", category: "Cameras", stock: 4, badge: "Limited", sold: 7 },
];

export const MOCK_ORDERS = [
  { id: "#1042", customer: "Fatima Ahmed", phone: "017XXXXXXXX", items: "iPhone 16 Pro x1", amount: "৳1,40,000", status: "Delivered", date: "Today", city: "Dhaka" },
  { id: "#1041", customer: "Hasan Mahmud", phone: "018XXXXXXXX", items: "Sony Headphone x1", amount: "৳35,000", status: "Shipped", date: "Yesterday", city: "Chittagong" },
  { id: "#1040", customer: "Nadia Khan", phone: "019XXXXXXXX", items: "MX Master 3 x2", amount: "৳19,000", status: "Pending", date: "2 days ago", city: "Dhaka" },
  { id: "#1039", customer: "Rahim Uddin", phone: "017XXXXXXXX", items: "Smart Watch x1", amount: "৳22,000", status: "Delivered", date: "3 days ago", city: "Sylhet" },
  { id: "#1038", customer: "Sadia Islam", phone: "018XXXXXXXX", items: "MacBook Air x1", amount: "৳1,35,000", status: "Cancelled", date: "4 days ago", city: "Dhaka" },
];

export const STATUS_STYLE: Record<string, string> = {
  Delivered: "bg-green-50 text-green-700",
  Shipped: "bg-blue-50 text-blue-700",
  Pending: "bg-yellow-50 text-yellow-700",
  Cancelled: "bg-red-50 text-red-600",
};